### ISSUE TITLE
 群晖 (Synology) 安装 Cloud Sync，挂百度云方法

### ISSUE THREAD

**Issue by hotoo** [hotoo/wiki#41]
1. 安装个Cloud Sync，已集成百度云、onedrive、dropbox、Google云盘等功能。
2. 首先进入Cloud Sync，选择百度云，登录绑定账号，选择一个文件夹作为同步文件夹。
3. 上网打开百度网盘，找到“我的应用数据”文件夹，打开进入可看到一个“Cloud Sync”文件夹。
4. 把百度网盘里的文件复制或移动到“Cloud Sync”文件夹，NAS过一会儿就会自动将相应内容同步下载到你前面选择的文件夹里面。同样，你将NAS的其他文件复制到你的同步文件夹，也会自动同步上传到百度网盘“Cloud Sync”文件夹。
5. 文件同步完成后，将NAS同步文件夹里内容移到其他文件夹，过会儿会同步删除百度网盘“我的应用数据”相应内容。所以提醒需要将NAS和网盘双向备份数据的朋友记得及时将“Cloud Sync”和同步文件夹内数据转移至其他文件夹，可以节省NAS空间占用。
## Ref
- http://www.hdpfans.com/thread-490429-1-1.html
- http://www.expreview.com/35401.html

**Comment by dongzhuming** [comment]
这个方案现在还能用吗？我连接好百度网盘后，无法看到网盘内任何文件

**Comment by dongzhuming** [comment]
是的，谢谢！
